[profile.default]
eth-rpc-url = "https://goerli.infura.io/v3/****"
libs = ["lib"]
out = "out"
remappings = [
  '@openzeppelin/=node_modules/@openzeppelin',
  '@uniswap/=node_modules/@uniswap/',
  'forge-std/=node_modules/@ecmendenhall/forge-std/src/',
  'ds-test/=node_modules/@ecmendenhall/ds-test/src/',
  'hardhat/=node_modules/hardhat',
  'erc721a/=node_modules/erc721a',
]
# solc = "0.8.15" # to use a specific local solc install set the path as `solc = "<path to solc>/solc"`
src = "tests/"

## set only when the `hardhat` profile is selected
[profile.hardhat]
libs = ["node_modules"]
out = "artifacts"
src = "contracts"

## set only when the `spells` profile is selected
[profile.spells]
## --snip-- more settings
